### ISSUE TITLE
Latest commit 16ac215

### ISSUE THREAD

**Issue by Shadow322** [roxas75/rxTools#338] opened 2016-01-06 01:58 UTC
Boots to 2 black screens o3ds ninjahax 1.1b booting method

**Comment by mxalbert1996** [comment] 2016-01-06 05:56
Same on O3DS and N3DS with CtrBootManager.

**Comment by urherenow** [comment] 2016-01-06 06:00
I've been trying to explain that to @173210

**Comment by sykhro** [comment] 2016-01-06 11:24
It worked for me after updating all the submodules (devkitpro, ctrulib, etc.)

**Comment by Shadow322** [comment] 2016-01-06 11:27
r45 and ctrulib 10?

**Comment by sykhro** [comment] 2016-01-06 11:29
Yes. I forgot, also use the latest CakeHax and CakeBrah

**Comment by urherenow** [comment] 2016-01-06 11:32
That's exactly what I've been using since r45 came out. This latest commit does not work for me. It builds, but nothing but black screen on 3DS.

Did you update ctrulib even more (post 1.0 commits) or are you building on Linux?

**Comment by sykhro** [comment] 2016-01-06 11:37
The OS shouldn't really matter, I'm using Linux though. devkitpro r45 (with the included ctrulib 1.0 and all) should work

**Comment by Shadow322** [comment] 2016-01-06 11:39
How do u get latest cakehax cakebrah?

**Comment by Shadow322** [comment] 2016-01-06 11:41
Can u upload your compiled copy to some file share site?

**Comment by urherenow** [comment] 2016-01-06 11:41
Then that's what I've been using. And everyone so far that says it doesn't work is building on Windows.

You get the latest Cakebrah and Cakehax by cloning mid-kid's repositories. Then replace the folders in rxtools with them.

**Comment by sykhro** [comment] 2016-01-06 12:43
I'm not home until tomorrow, will upload asap

**Comment by mxalbert1996** [comment] 2016-01-06 14:02
When I checkout commit d1cbd47 and compile I can launch it. But commit 16ac215, no. Built on Ubuntu.

**Comment by urherenow** [comment] 2016-01-06 14:13
Then I stand corrected. So right now, there are only 2 people that "claim" this commit works, and I've confirmed that @173210 didn't even start from scratch. He only copied over the .bin file.

That does NOT count as a working test.

**Comment by 173210** [comment] 2016-01-06 14:16
@urherenow I have tested from scratch after that. It works fine. :/

**Comment by urherenow** [comment] 2016-01-06 14:24
@AlbertoSONIC did you get yours working?

**Comment by AlbertoSONIC** [comment] 2016-01-06 14:25
Nope

Il giorno mer 6 gen 2016 alle 15:24 urherenow <notifications@github.com> ha
scritto:

**Comment by AlbertoSONIC** [comment] 2016-01-06 14:27
And I need rxTools working to continue AdvancedFileExplorer developement :(

**Comment by Matsumot0** [comment] 2016-01-06 15:17
i can confirm, same issue compiled on debian 8 x64
Black screen both TOP/BOT

**Comment by sykhro** [comment] 2016-01-06 15:20
If the situation is that bad, can't you reset the master branch to d1cbd47?

**Comment by urherenow** [comment] 2016-01-06 15:24
Ok, @173210 I just cloned 173210/rxtools and all of the files in /sys have the same hash as ones produced with roxas75/rxtools, except for code.bin. I would ask why that is, except that it also leaves me with a black screen launching from menuhax->ctrbootmanager and from ctrbootmanager->HBL->rxTools.3dsx.

**Comment by Syphurith** [comment] 2016-01-07 02:11
@urherenow Oh no You don't need that. Black screen might due to wrong addresses of Frame Buffers (direct cause), as supposed the TMIO is NAND related thus if it can boot it confirms this is working. I am still using an old build. You may check the commit history for diffs between this and an working version.

**Comment by Syphurith** [comment] 2016-01-07 02:32
If you think #336 caused the issue I have to say this is NAND related driver, and should not infect the FrameBuffer that much. You can just check out 0733322dfdf0588c4908d1e50e974e8dfba6d91c to see if working, not 16ac2157fadb758774f891c383fe1af1fd16f290.
There is still commits between its committed and merged time.

**Comment by urherenow** [comment] 2016-01-07 04:25
@Syphurith @173210 @AlbertoSONIC 895bf35 works. AutoBooting to RX-E breaks at bf9f0a1 (and it seems that replacing code.bin resets your config every time, so it tries to autoboot instead of showing the UI. If I hold L when loading bf9f0a1, it will work.

at 0733322, holding L doesn't even help. It is broken on both my o3ds and n3ds.

The issue may very well be entirely because of the stub.ld changes. Were those changes necessary for 0733322 and above, or would it be safe to revert stub.ld to where it was at 895bf35?

**Comment by urherenow** [comment] 2016-01-07 04:37
nah. Just tried and replacing stub.ld and that didn't fix it either. I'm late for work again... It was kind of fishy at bf9f0a1, and completely breaks at 0733322.

**Comment by mxalbert1996** [comment] 2016-01-07 04:49
@urherenow bf90a1 is OK for me. No problem with Data Installation and AutoBooting.

**Comment by Syphurith** [comment] 2016-01-07 04:51
stub.ld is telling linker how to link the executable. This could cause some problems if sections aren't properly placed in RAM. However your result telling me this doesn't matter much.
Thanks for your effort. And i don't know why neither, then (orz) Sorry.

**Comment by urherenow** [comment] 2016-01-07 05:13
@mxalbert1996 it may have been a 1 time glitch. As I said, it worked after I held L to boot it. 0733322 is what doesn't work no matter what I try.

**Comment by urherenow** [comment] 2016-01-07 05:17
@Syphurith well, telling it how to link stuff up absolutely says why using the old stub.ld doesn't work in the newer commit. 

But if the linking was the issue, there is no way it would work on 2 people's machines.

**Comment by 173210** [comment] 2016-01-07 05:19
@urherenow It may depend on libc, which uses symbols defined in `stub.ld`. Did the recent devkitPro update libc?

**Comment by urherenow** [comment] 2016-01-07 05:28
maybe?
•binutils updated to 2.25.1.
•gcc updated to 5.3.0.
•gdb updated to 7.10.0.
•3dslink now takes --retries parameter to set number of pings before it gives up.
•Added picasso - a pica200 shader assembler.

libnds 1.5.12
•Improved DSi SD card support.
•Added DSi NAND access.
•Fixed several compiler warnings.

default arm7 0.6.0
•Rebuilt with latest libraries.

libctru 1.0.0
•The long awaited great refactor goes mainstream :)

**Comment by Shadow322** [comment] 2016-01-07 07:32
Does it compile correctly under windows now without black screens?

**Comment by urherenow** [comment] 2016-01-07 07:50
No.

**Comment by urherenow** [comment] 2016-01-07 08:13
I'm not smart enough to figure out the stub.ld thing. There is a TON of stuff that was simply removed, and a bunch of it looks important to me. I don't see how it could possibly work at all for @sykhro or @173210 , if it's what it breaking my device :/. Still, they are the only two that have stepped up and said it works for them. For the ones that are working, which model (o, n, 2) and firmware are you running this on, and launching by which method?

**Comment by 173210** [comment] 2016-01-07 08:23
@urherenow In fact, nothing of them are important. But, newlib, modified by devkitPro, uses `__end__` symbol for `sbrk`, so I left it. The newlib modification is sort of a dirty hack, but actually it works.
old 3DS 9.2J
new 3DS 9.2J

**Comment by urherenow** [comment] 2016-01-07 08:24
and the specific ram = 0xff stuff and alignment?

**Comment by 173210** [comment] 2016-01-07 08:28
@urherenow Yes. `= 0xff` is simply unnecessary. It's just padding. The LD is not so foolish, and the alignments should be done automatically if you wrote `.align 2` in your (assembly) source file. I have also confirmed that using readelf. (I can't trust the standard libraries, so I also confirmed that they don't break the alignments,)

**Comment by urherenow** [comment] 2016-01-07 08:31
I shouldn't bother with it anyway. The majority of .ld changes were in a commit that works anyway and only 1 line was added to it in 0733322. Something else is breaking it.

**Comment by 173210** [comment] 2016-01-07 08:33
@urherenow The added line is very important. `.test.start` should be just after `.text.vect`; otherwise it will crash.

**Comment by urherenow** [comment] 2016-01-07 08:41
Well, there are 3 differences between our builds. Devkitpro, Cakehax, and Cakebrah. The submodules shouldn't have an issue because I've tried using a fresh rxtools tree, only making the changes needed to compile under ctrulib 1.0.

**Comment by urherenow** [comment] 2016-01-07 13:27
Just did a build with an exact clone, and a fresh install of devkitARM r44. Same result; black screen.

I find it odd though, that CakesROP seems to requires libnds from like 26 days ago if others are building this with r44 (before that, there is no fat.h and such)..

**Comment by sykhro** [comment] 2016-01-07 13:35
I'm using a n3ds J 9.1 
I'm moving so I have no home internet. Will post my build asap

**Comment by urherenow** [comment] 2016-01-07 13:39
Great... so it's only working with Japanese consoles? That's a twist... does anyone without a Japanese console have this working?

**Comment by mxalbert1996** [comment] 2016-01-07 14:36
I've got a JPN N3DS but it's not working on it.

**Comment by urherenow** [comment] 2016-01-07 16:28
What firmware?

**Comment by mariogamer2** [comment] 2016-01-07 16:45
Hava a 2ds USA,but can't test now,I hope tomorrow.

**Comment by piorrro33** [comment] 2016-01-07 17:04
Confirmed here as well, black screen with a freshly compiled copy on O3DS 9.2.0-20E. I hope that helps.

**Comment by mxalbert1996** [comment] 2016-01-07 18:13
@urherenow 9.1

**Comment by urherenow** [comment] 2016-01-07 22:21
Can Japanese consoles be set to English? If so, @173210 or whomever else has this working, please change your settings to English and try (or @mxalbert1996 if yours it set to English right now, change it to Japanese and see if it magically starts to work for you). I've been watching ctrulib on GitHub as well and it just popped in my head as I was waking up to get ready for work, that there is a problem with ctrulib https://github.com/smealum/ctrulib/issues/239 which you would think would have nothing to do with rxtools since it doesn't use ctrulib, (except that both Cakebrah and Cakehax use it) but @WinterMute mentioned "The console doesn't support unicode of any form atm either.". One of the things done for 0733322 was something to allow Unicode file names, right?

I know this sounds silly, but I'm grasping at straws now. Just humor me please. My USA console can't be switched to Japanese.

**Comment by Desterly** [comment] 2016-01-08 03:41
Well after playing around w/ this a bit, it seems to me it's something with the tmio drivers.  The rest of the changes check out clean. 

I left everything in except reverted back to the sdmmc drivers and it boots up fine

**Comment by 173210** [comment] 2016-01-08 04:05
By the way, `DrawString` is useful for debugging because it doesn't use libc and TMIO driver.

**Comment by mxalbert1996** [comment] 2016-01-08 04:30
@urherenow No. The language of JPN consoles can only be Japanese.

**Comment by urherenow** [comment] 2016-01-08 05:23
So the quick fix is to get rid of the TMIO driver. But why does it work for 2 people and no one else? It must be a timing or format thing, no?

**Comment by Shadow322** [comment] 2016-01-08 05:26
@urherenow can u build a working copy and upload it?

**Comment by AlbertoSONIC** [comment] 2016-01-08 05:29
@173210 Why don't you upload your code.bin? Maybe it's a compilation issue, it compiles well for you, it doesn't for me ;)

**Comment by 173210** [comment] 2016-01-08 05:29
@urherenow The patch itself is to fix the timing. The old `sdmmc.c` didn't wait for the device, so it had a problem when it was compiled in different options (such as -O0 or -mthumb). My driver has solved the problem and confirmed it works both on ARM and Thumb state. (note that the driver in this pull request can't be compiled in Thumb state because it uses `mcr` instruction as an inline assembly)

**Comment by urherenow** [comment] 2016-01-08 05:29
After work. If not then some time tomorrow. I'll just do another link to a code.bin since that seems to be the only problem file.

**Comment by urherenow** [comment] 2016-01-08 05:33
@173210 all the patch did was completely break rxtools for everybody except you, and 1 other person. Whatever timing problems you think sdmmc had pale in comparison.

**Comment by 173210** [comment] 2016-01-08 05:34
Wait, do you use SDHC or normal SD?

**Comment by urherenow** [comment] 2016-01-08 05:39
I think it's different between o3ds and n3ds, but I'm sure at least one uses sdhc and probably even sdxc.

**Comment by Shadow322** [comment] 2016-01-08 06:42
So replace the code.bin from previous comment to this one?

**Comment by urherenow** [comment] 2016-01-08 07:12
My previous code.bin is a broken one. I was hoping @173210 would see if it works on his system. Give me a bit and I'll try to get a working one with the sdmmc driver put back. I'm just getting home from work...

**Comment by urherenow** [comment] 2016-01-08 07:15
Or not... "Updating Windows. Your PC will restart several times"

Shit.

**Comment by urherenow** [comment] 2016-01-08 07:17
@173210 o3ds: SDHC. N3DS: SDXC. Both don't work.

**Comment by urherenow** [comment] 2016-01-08 08:36
Ok, rebuilt with latest tree, but reverted all TMIO stuff, and it works without a hitch! Working code.bin here: https://www.dropbox.com/s/4kyq1ibhjjoomam/Working_code.bin.zip?dl=0

**Comment by urherenow** [comment] 2016-01-08 13:01
figured out how to push it to my fork, then make the pull request. @AlbertoSONIC if you merge #340, it will fix this issue and doesn't seem to affect commits after that. It works on my systems and a resulting code.bin is linked in my post above, if you would like to test first.

**Comment by Desterly** [comment] 2016-01-08 13:35
@173210 : what was the upstream source for the tmio commits?   I ask because the sdmmc code in CakeHax matches very close to the tmio driver.

I'm wondering if a better route would be to stick with sdmmc but update it from what CakeHax has.

**Comment by AlbertoSONIC** [comment] 2016-01-08 13:46
So I just revert? (By merging @urherenow PR)

**Comment by Desterly** [comment] 2016-01-08 13:51
Personally I'd just revert the pull request for now instead of adding a new one to do the revert...

https://help.github.com/articles/reverting-a-pull-request/

**Comment by AlbertoSONIC** [comment] 2016-01-08 14:07
Ok I revert it ;)

**Comment by 173210** [comment] 2016-01-08 14:38
It's not different from merging the PR. Git will record everything, including a reverting change as a commit.

**Comment by AlbertoSONIC** [comment] 2016-01-08 14:39
Yeah.. @173210 Check your email inbox ;)
Il giorno ven 8 gen 2016 alle 15:38 173210 <notifications@github.com> ha
scritto:

**Comment by urherenow** [comment] 2016-01-08 15:44
@AlbertoSONIC NO! Too late I guess though. @Desterly how are you going to come in here out of nowhere and make a suggestion without knowing what you're talking about? There really was a change in that commit to start.s that needed to stay put. My PR would have done this correctly. Now another pull request needs to be done anyway to fix 1 line. SMH.

**Comment by urherenow** [comment] 2016-01-08 15:54
Well, actually I don't know that it matters, since it went completely back from @173210 's original rewrite. I guess he should comment on whether or not it improved or optimized anything.

**Comment by Desterly** [comment] 2016-01-08 16:02
@urherenow no harm intended... I was simply stating it be cleaner to do a revert and then go forward then to introduce an additional commit.. sorry if it caused problems.

**Comment by urherenow** [comment] 2016-01-08 16:28
I wouldn't say "caused problems" as the old stub.ld works. The rewritten stub.ld was so much cleaner, smaller, and I'm not sure if it optimized anything as a result (it may have). I'm mainly disappointed that I spent an hour reverting that commit by hand, while leaving that one file alone, and then spending another hour or so figuring out how to get it online for a pull request (I'm still very new to github).

I feel like my time was wasted.

**Comment by mxalbert1996** [comment] 2016-01-08 17:08
@urherenow I think you could simply grab d1cbd47 and apply the new stub.ld to it. Cause github displays commits in time order but actually when d1cbd47 was commited, bf9f0a1 and 0733322 haven't been merged.

**Comment by Desterly** [comment] 2016-01-09 05:02
Well after all of that, I figured out what the problem was.  my US oDS3 now boots with the TMIO driver..

all that needs to be done (for U.S.) is change ffconf.h from:
#define _CODE_PAGE 932
to
#define _CODE_PAGE 437

and add back in the ccsbcs.c file to option.

Still trying to track down why the old fs driver was ignoring codepages though.

**Comment by Desterly** [comment] 2016-01-09 05:48
Found it.   The old ff.c driver was hard coding the unicode conversion to US char set (437).  The new one didn't have that patch in it.
I'm not sure how it was working for non US people before though unless their devices/FS uses an odd unicode setting.

Regardless,  it needs more testing but changing the code page and adding the ccsbcs.c file back makes TMIO useable

**Comment by mxalbert1996** [comment] 2016-01-09 06:57
@Desterly Great! It works on both my USA O3DS and JPN N3DS!

**Comment by 173210** [comment] 2016-01-09 07:09
@Desterly It is because 437 is SBCS, while 932 is DBCS.

**Comment by Desterly** [comment] 2016-01-09 17:22
There's still something up with this.  the files generated for the pads are wrong..
〯〴〰㔲⸰湩桸敤潸摡 - that's the file name that gets saved on the sdcard.

**Comment by Desterly** [comment] 2016-01-09 17:57
Nevermind...  i see the problem.  the nchhinfo isn't in unicode.

**Comment by mxalbert1996** [comment] 2016-01-09 18:06
@Desterly How did you solve it? I created ncchinfo.bin using 3DS Simple CIA Converter and it generated the same file name. Do you mean the encoding of the file matters?

**Comment by urherenow** [comment] 2016-01-09 18:09
@Desterly probably why:

@WinterMute mentioned "The console doesn't support unicode of any form atm either".

**Comment by Desterly** [comment] 2016-01-09 18:11
@mxalbert1996 I haven't yet.. looking at it.  That's what I was using too.  3DS Simple CIA Converter embeds the file name in a non-unicode format.   with the new parser, we require unicode.   Decrypter9 has some code to handle it so I'm looking to see what he did there

**Comment by Desterly** [comment] 2016-01-09 21:05
This probably should be taken to a new issue... even if I pull down clean source I get the same odd file name issue.    
Could be an issue with CakeBrah or CakeHax updates?

**Comment by AlbertoSONIC** [comment] 2016-01-10 10:07
Ok It's time to close this ;)

**Closed by AlbertoSONIC** 2016-01-10 10:07 UTC
