### ISSUE TITLE
GBA not working in emuNAND (missing patches in rxtools/sys/patches?) - New 3DS, emuNAND 9.5.0-23E

### ISSUE THREAD

**Issue by Keizel** [roxas75/rxTools#306] opened 2015-11-15 15:16 UTC

**Comment by 173210** [comment] 2015-11-15 21:59
It's not supported, so it should be a new feature.

**Comment by Keizel** [comment] 2015-11-15 23:33
Before I can load GBA roms in emuNAND, now I can not do it... Why?

**Comment by 173210** [comment] 2015-11-16 00:00
@Keizel Because now it tries to load AGB_FIRM for rxMode, which is not available.

**Comment by Keizel** [comment] 2015-11-16 01:11
It will add?

**Comment by 173210** [comment] 2015-11-16 03:03
@Keizel Can you test #305?

**Comment by 173210** [comment] 2015-11-16 03:23
@Keizel Sorry, I confirmed the patches is not enough. ARM9 is encrypted. :(

**Comment by capito27** [comment] 2015-11-16 11:50
i can confirm, i tested #305 with a pokemon emerald cia, the reboot happened and then blackscreen. if that may help

**Comment by 173210** [comment] 2015-11-16 12:13
rxMode doesn't support AGB and TWL. They will never work with the current code.
By the way, the issue is not because of the lacking patch. Please change the title.

**Comment by Keizel** [comment] 2015-11-16 12:14
Before for use GBA in emuNAND was necessary install AGB_patched for use games of GBA and install the games in sysNAND and emuNAND, when you did it, you could try load the game in emuNAND, then you go directly to play in sysNAND through load it in emuNAND. Before it was possible.

**Comment by 173210** [comment] 2015-11-16 12:16
@Keizel I know that. But I killed it for rxMode patching. And rxMode doesn't support AGB and TWL so it crashes.

**Comment by Keizel** [comment] 2015-11-16 12:18
Sorry for annoy, but as before I could use the rxTools in emuNAND and play the GBA games...

**Comment by capito27** [comment] 2015-11-16 12:35
So if i understood properly, @173210, now RxMode doesn't patch TWL and AGB reboot code anymore so it doesn't work. Is it planned to bring back that function someday or not ?

**Comment by 173210** [comment] 2015-11-16 12:37
@capito27 It can't load those FIRMs even without patches. I have no plan to support them (although @AlbertoSONIC persists with them).

**Comment by capito27** [comment] 2015-11-16 12:46
ok, then i am now gonna close this issue, since this is more of a feature removal rather than a bug.
@Keizel you can always open a new issue labeled as enhancement if you wish for them (AGB/TWL patching) to be brought back (but doing so is obviously not a promise that anything will happen,)

**Closed by capito27** 2015-11-16 12:46 UTC
