### ISSUE TITLE
Generation of XORPads doesnt work

### ISSUE THREAD

**Issue by sweatboxx** [roxas75/rxTools#167] opened 2015-08-12 08:48 UTC
i tried afc001e and noticed, that the xorpad generation doesnt work.
Tried the ncchinfo.bin from 3ds simple cia converter in root and rxtools and rxtools/system

Downgraded to 2.6 and it works pretty well.

My 3DS is an old 3DS XL with 4.5.0-8E

**Comment by dukesrg** [comment] 2015-08-12 11:20
@sweatboxx Can you describe what is happening?

**Comment by sweatboxx** [comment] 2015-08-12 11:49
yeah ofcause.
In 2.6 the display switch to another screen and shows some strings and percent values.
In the tested nightly the screen keeps and the 3ds doesnt reakt on inputs (up, down, b, a, ...).

**Comment by dukesrg** [comment] 2015-08-12 12:49
@sweatboxx thanx, just fount an issue. Will be requested to merge tonight.

**Comment by dukesrg** [comment] 2015-08-12 17:55
@sweatboxx Should be fixed with #174

**Comment by sweatboxx** [comment] 2015-08-12 19:34
Thx.  Will try it soon and report if it works or not.

**Comment by sweatboxx** [comment] 2015-08-16 16:48
Worked. Have now only a view error. 
When the prozess has no 100 %, it like 66%%. But it's OK. 

Thanks for the fast solution.

**Comment by dukesrg** [comment] 2015-08-16 17:36
@sweatboxx So just a progress display error? OK I'll have a look in 2 weeks when back from vacations, keeps this issue open if nobody else fixes that.

**Comment by sweatboxx** [comment] 2015-08-17 04:37
Yeah it's only a progress display error. 
It's not really important. So enjoy your two weeks.

**Comment by maki-chan** [comment] 2015-09-10 15:03
I can confirm that. Xorpad generation works great, but the display doesn't clean itself right. After the first partitions are through with instant 100% due to their size, the display shows `0%0%` because it doesn't clean the line completely and the last `0%` from the `100%` progress are a left-over. It changes to `10%%` and so on until it's `100%` again.

**Closed** 2015-11-18 06:06 UTC
Labels: bug
