### ISSUE TITLE
Black bottom screen

### ISSUE THREAD

**Issue by thiagokokada** [roxas75/rxTools#279] opened 2015-10-30 02:00 UTC
Compiled commit cbec77e, put everything that is needed (`firm` folder on `/rxTools/sys`, including `cetk`  file). It works, however the bottom screen is always black, so if you try to change some settings or do anything that isn't booting emuNAND, it is very difficult since you have to guess which option you're currently (top screen works fine).

O3DS with sysNAND version 9.2.0-20U, emuNAND 10.2.0-28U. Booting rxTools using themehax 2.5, autoboot version. As for the payload, I am using my [HBL-Emergency](https://github.com/m45t3r/HBL-Emergency) to direct boot the `code.bin` file (it uses CakeBrah). While it could be my fault, older builds works for me.

**Comment by 173210** [comment] 2015-11-01 04:32
Identified: The issue can be fixed by applying the following patch to CakeHax. I don't know why.
[code]diff --git a/source/payload/main.c b/source/payload/main.c
index d16306b..cc046c6 100644
--- a/source/payload/main.c
+++ b/source/payload/main.c
@@ -62,6 +62,7 @@ void main()
     *(uint32_t *)0x080FFFC0 = (uint32_t)framebuffers->top_left;
     *(uint32_t *)0x080FFFC8 = (uint32_t)framebuffers->top_right;
     *(uint32_t *)0x080FFFD0 = (uint32_t)framebuffers->bottom;
+    *(uint32_t *)0x080FFFD4 = (uint32_t)framebuffers->bottom;
 
     // Select the first framebuffer for each screen, since we only write that one.
     *(uint32_t *)0x080FFFD8 = 0;[/code]

**Comment by Syphurith** [comment] 2015-11-01 04:43
@173210 Eh.. I don't know either. No `0x080FFFD4` ever appeared in current source code, but `0x08FFFD0` does.. I don't know if the build was done really clean with latest submodules..

**Comment by 173210** [comment] 2015-11-01 04:46
It was by chance, sorry. @Syphurith

**Comment by Syphurith** [comment] 2015-11-01 04:49
@173210 Eh.. Searched for the file `draw.h` in the git log. This address was used as `BOT_SCREEN2` before, and it was messed up with the other in some commits. I don't know if we need both to draw properly, or just one - then which one is actually needed..
@m45t3r Mind you please show me your compiled binary ELF? I wanna know if you've compiled it all correctly so no address is messed up.

**Comment by 173210** [comment] 2015-11-01 04:58
Truely Identified: Commit b7361b8b9eae1cc59135c0cd282fe2480ef80d47 (aka cf42c2d9d0a552a8b82ba1a4c42acb91022c0ef6) in CakeBrah makes it unstable and keep the bottom screen black. The problem is of CakeBrah, so I'll open issue #281 again.
By the way, @m45t3r has a problem even on old one. It may be because CakeHax is old.

**Comment by Syphurith** [comment] 2015-11-01 05:01
@173210 Oh.. Okey. You're quite effective on finding the commit, cheers. *Have your good day.*

**Comment by m45t3r** [comment] 2015-11-01 07:29
@Syphurith here you go.

http://a.pomf.hummingbird.moe/cxdyqa.elf

**Comment by AlbertoSONIC** [comment] 2015-11-01 09:12
I think rolling back to a working CakeHax and CakeBrah is our best choice (until they get fixed)

**Comment by 173210** [comment] 2015-11-01 09:16
@m45t3r Is CakeHax the latest?

**Comment by Syphurith** [comment] 2015-11-01 09:19
@m45t3r Thanks for that. I would test which bottom buffer address you used.

**Comment by Syphurith** [comment] 2015-11-01 09:38
@m45t3r Checked your ELF, all those `BOT_SCREEN` used are `0x080FFFD0`. I'm sorry for that. It seems Cake Stuffs have some problems to overcome. *And i didn't find where the address is passed in my own repo.. So won't ask you for the file again.* Hope @mid-kid can figure out what happened.

**Comment by Steveice10** [comment] 2015-11-01 14:54
FYI this is how CakesFW accesses the framebuffer after CakeBrah, which you don't seem to be doing (unless I've missed something?)

https://github.com/mid-kid/CakesForeveryWan/blob/master/source/draw.c#L7

**Comment by m45t3r** [comment] 2015-11-01 15:08
@173210, if you mean my homebrew, yeah. I actually use a fork of CakeBrah, named [libcakebrah](https://github.com/m45t3r/libcakebrah). However it is up-to-date with upstream.

**Comment by soarqin** [comment] 2015-11-01 15:18
I think it is better to fork CakeBrah and CakeHax out for rxTools use to keep codes in-sync

**Comment by AlbertoSONIC** [comment] 2015-11-01 15:23
@soarqin Yeah I think so

**Comment by mid-kid** [comment] 2015-11-01 19:29
@soarqin please no. If you need a specific revision of any of them, just use that. If something's missing/wrong and you want to change that, please tell me instead. No need for useless forking unless the repo owner is not going to do anything about it, or you want to do something completely different with it. It just adds more work to maintain the fork. (I'll be merging libcakebrah as soon as I find time to look at it carefully).
As for CakeHax, the only thing I've changed recently is this: https://github.com/mid-kid/CakeHax/commit/c762a2110f118ccba2aa30564eb2b460c4ac8f7e
It would appear that the offsets were wrong, and since I meant to setup a similar environment to Gateway's with that payload, I corrected it. rxTools should update to those offsets accordingly (if that's needed at all).
Other than that, I haven't done any breaking changes (or changes at all) in a pretty long while, so if it worked before, it should still work.

**Comment by 173210** [comment] 2015-11-02 00:25
@m45t3r I mean, CakeHax included in rxTools/sys/code.bin.
@mid-kid :+1:

**Comment by soarqin** [comment] 2015-11-02 01:02
@mid-kid forks are used to keep branch HEADs in sync with rx HEADs, we would still send PRs to upstream if there is any fixes

**Comment by m45t3r** [comment] 2015-11-02 01:06
@173210 I am pretty sure I did a git submodule update, so it should be correct.

**Comment by 173210** [comment] 2015-11-02 01:09
@soarqin Isn't an old revision enough? That's why "git submodule" doesn't track HEAD.
@m45t3r Hmm, it's strange. It works fine for me. I'm using old 3DS 4.5.0 and MSET.

**Comment by urherenow** [comment] 2015-11-02 02:56
I just updated everything; Ninjhax to 2.5 and latest HBL, also used menuhax 2.0 for fun. On my N3DS, I can no longer duplicate this problem. I had it while trying to launch via Ninjhax 1.1b and an older HBL.I do not use autoboot though. I have to hold the L button for themehax (I need it this way since I use Gateway as well via MSET).

**Comment by m45t3r** [comment] 2015-11-02 16:59
Well, my submodules was really out-of-date (I did some git checkouts to try to get a good commit, and probably in one of them I downgraded my submodules too and forget to upgrade again). Doing a git submodule update did the trick, and know I can't reproduce this bug anymore in my O3DS.

**Comment by m45t3r** [comment] 2015-11-04 02:03
I did a clean compile today (deleted the older folder since it was a mess, ``git clone --recursive; make release``), deleted the old rxTools folder in the root of my SD card and put the newly compiled one in my O3DS, including ``firm`` folder with ``cetk`` file.

The *Instalation Suite* screen appeared, however the bottom screen was black (it didn't showed the squares indicating the installation progress). Well, at least after I rebooted the O3DS and started rxTools again with menuhax 2.0, pressing R to show the menu, the configuration screen appeared.

The strange thing is, the last time I compiled using lastest commit (ac330f0), I am sure the bottom screen during installation appeared as it should, so it seems somewhat random?

**Comment by Syphurith** [comment] 2015-11-04 02:45
@m45t3r Randomly? That's quite weird. But for me, It seems you should clear the `sd:/rxTools/data` first in order to trigger a normal installation. I even faced a totally black screen before i tried so.

**Comment by m45t3r** [comment] 2015-11-04 04:32
@Syphurith I deleted my rxTools folder (with the exception of ``firm``), so this shouldn't be the problem.

**Comment by Syphurith** [comment] 2015-11-04 05:07
@m45t3r Oh well.So there is some issues with it. My apologize.

**Comment by AlbertoSONIC** [comment] 2015-11-18 14:12
I tried to boot rxTools 10 times, here are the results:
1 time the gui was fine
5 times the bottom screen stayed black, only top screen shown
4 times both the screens were black

**Comment by urherenow** [comment] 2015-11-18 16:12
I don't get this using menuhax+ctrbootmanager on the N3DS. Must be O3DS only. I do have to try a few times to boot, but when it works, it works.

**Comment by AlbertoSONIC** [comment] 2015-11-18 16:15
I use bootCtr + homemenuhax on N3DS

Il giorno mer 18 nov 2015 17:13 urherenow <notifications@github.com> ha
scritto:

**Comment by AlbertoSONIC** [comment] 2015-11-18 22:39
No no you misunderstood. rxTools always boot on  ctrBoot! But sometimes screens stay black and I have to press buttons "blindly" ;)

**Comment by m45t3r** [comment] 2015-11-18 22:52
Just make it clear if you're using CtrBootManager or BootCtr. While they are similar, they are completely different projects.

I can't really help with CtrBootManager, since I am the author of BootCtr.

**Comment by urherenow** [comment] 2015-11-18 23:07
@AlbertoSONIC is using bootCTR. Apparently, it has a high rate of success, but the rxtools menu is messed up when he wants to use the menu.

I use ctrbootmanager. My success rate is lower than his, but I have no problems with the menu.

**Comment by 173210** [comment] 2015-11-19 02:50
Obviously the issue is in CakeBrah, not in rxTools. This issue should be closed and to be fixed in CakeBrah.

@mid-kid I tried to open an issue in your repository but its issue page doesn't seem enabled.
@urherenow It works fine every time. Maybe the timeout option may fix your issue. (I always open the menu.)

**Comment by mid-kid** [comment] 2015-11-19 08:11
CakeBrah works fine for me, except there's a few times when it doesn't start at all, but that's probably when escalating privileges. It always worked well with hax2.1, and while hax2.5 has changed some things in that respect, I've never had any issue with the framebuffers. If it doesn't boot, it just doesn't boo at all, and I don't get no or garbled framebuffers. I'm using no bootmanager at all.
But okay, issues in CakeBrah are open, if you want to do the discussion there.

**Comment by 173210** [comment] 2015-11-19 10:13
@mid-kid I suspect libkhax even for this issue as well boot rate, but I have no evidence. Thank you for enabling issue tracker.

**Comment by 173210** [comment] 2015-11-19 10:34
I read libkhax source code for the first time and found it doesn't deal with cache and write buffer correctly.

KHAX::MemChunkHax::Step5_CorruptCreateThread(): Doesn't flush instruction cache
https://github.com/Myriachan/libkhax/blob/93fdb60c1dff9fc45a885c1fd582209604fd5e01/khaxinit.cpp#L529

KHAX::MemChunkHax::Step6f_FlushCaches(): Doesn't flush write buffer.
https://github.com/Myriachan/libkhax/blob/93fdb60c1dff9fc45a885c1fd582209604fd5e01/khaxinit.cpp#L762

Instruction cache can be flushed even in user mode in this way, according to HANS.
https://github.com/smealum/HANS/commit/9ee5581af2d2800eade986c5cc14814a8c706e9a#diff-816bb7e736f9cf161e1a3be0fe048607R264
```C
	Result ret = NSS_LaunchTitle(&nssHandle, 0x0004013000002A02LL, 0x1);
	if(ret)return ret;

	svc_sleepThread(100*1000*1000);

	ret = NSS_TerminateProcessTID(&nssHandle, 0x0004013000002A02LL, 100*1000*1000);
	if(ret)return ret;

	print_str("invalidated icache\n");

	return 0;
```

Here is a code to drain write buffer.
```C
__asm__ volatile ("mcr p15, 0, %0, c7, c10, 4\n", 0);
```

**Comment by 173210** [comment] 2015-11-19 10:42
Instruction cache also seems to be flushed by user mode instructions.
```
__asm__ volatile ("mcr p15, 0, %0, c7, c5, 4\n" :: "r"(0));
```

**Comment by hartmannaf** [comment] 2015-11-19 10:58
@173210 Why aren't you using the newest the libkhax commit for the links,the things you said would not have been changed?

**Comment by 173210** [comment] 2015-11-19 10:59
@hartmannaf I showed the commit which introduced the code.

**Comment by 173210** [comment] 2015-11-19 14:19
I removed all cache related code in libkhax and rewrite myself. Yes, it works. (4 / 4 trials) It was just a piece of cake.  :)
I'll clean up code and make a pull request tomorrow (it's 23:00, so I'll go to bed. I wonder why I stay up.)

**Comment by kot2002** [comment] 2015-11-19 14:57
Great job! @173210 Without you, stable release wouldn't be possible.

**Comment by 173210** [comment] 2015-11-20 00:41
I opened Myriachan/libkhax#9. But it doesn't seem enough. CakeBrah crashed in priv_firm_reboot, which is not in libkhax. :/

**Comment by 173210** [comment] 2015-11-20 01:17
I opened mid-kid/CakeBrah#5.

**Comment by 173210** [comment] 2015-11-20 23:43
I found it can crash after calling _KernelSetState. It's rare, but actually sometimes it crashes.

**Comment by 173210** [comment] 2015-11-21 03:07
Ok, I finally succeeded in fixing CakeBrah completely. (8 successes / 8 trials)
I'll push it later.

**Comment by m45t3r** [comment] 2015-11-21 04:13
@173210 So I can finally remove that ugly delay hack from BootCtr? Yay.

**Comment by 173210** [comment] 2015-11-21 04:14
@m45t3r My solution is to improve ugly delay hack in CakeBrah :(

**Comment by 173210** [comment] 2015-11-21 05:34
Updated mid-kid/CakeBrah#5.

**Comment by urherenow** [comment] 2015-11-21 05:47
So do we wait until libkhax and Cakebrah stuff is merged, or is it already ok to do a recursive clone of rxtools and build? 

If it's the latter, shouldn't this issue be closed?

**Comment by kot2002** [comment] 2015-11-21 06:05
@urherenow Learn about git's submodule https://git-scm.com/book/en/v2/Git-Tools-Submodules

**Comment by urherenow** [comment] 2015-11-21 06:29
Thanks for the link! But on my phone it's still hard to tell if the pull requests were accepted and merged yet...

**Comment by urherenow** [comment] 2015-11-21 07:06
Actually, it wasn't merged yet :(

**Comment by m45t3r** [comment] 2015-11-22 18:30
I compiled BootCtr using the fork made by @173210 in here if someone want to test: https://gbatemp.net/threads/re-release-bootctr-a-simple-boot-manager-for-3ds.401630/page-2#post-5821932

Probably this is more interesting for N3DS users, since for O3DS it seems that the old delay did the trick.

**Closed** 2019-04-24 23:40 UTC
Labels: bug
