### ISSUE TITLE
Extended Ram Games Not working

### ISSUE THREAD

**Issue by DaemonKun** [roxas75/rxTools#163] opened 2015-08-11 14:49 UTC
Built the latest repo. Extended Ram games are not booting.

**Comment by kot2002** [comment] 2015-08-17 15:00
I think this issue was made since filepack was removed.
Commit 173210@5848ed9ddaacc587f2c0151d4b2fa3f2de9d8884 caused this problem, maybe.

**Comment by kot2002** [comment] 2015-08-21 17:07
@173210 , I found which commit made this bug : cc33af00514e5991f7b2c1eab731f738ee14a3e3

**Comment by soarqin** [comment] 2015-08-21 18:52
memcmp thing @ line 236?

**Comment by 173210** [comment] 2015-08-22 00:53
@soraqin, memcmp seems OK. I think some patches in native_firm.elf have bugs.

**Comment by soarqin** [comment] 2015-08-22 06:04
@173210 I don't think so. This commit had not changed anything in native_firm.elf, but just moved patch timing to firm launch. If there were some bugs in native_firm.elf, the issue should have been appeared earlier

**Comment by 173210** [comment] 2015-08-22 06:43
@soarqin This change removes hardcoded values. It may invoke potential bugs (especially in the emuNAND patch) .
https://github.com/roxas75/rxTools/commit/cc33af00514e5991f7b2c1eab731f738ee14a3e3#diff-ac6385ab3288b4029e1cbeaedd4d9507L248

**Comment by soarqin** [comment] 2015-08-23 05:22
@173210 those hardcodes patches are only used to revert patch values while booting to sysnand, I don't think that affects emunand patches.

**Comment by DaemonKun** [comment] 2015-08-28 15:45
no fix yet?

**Comment by kot2002** [comment] 2015-08-29 12:12
Not yet. The source code has revised so many time after the commit caused that bug, so I don't have an idea how to fix it now.

**Comment by 173210** [comment] 2015-08-29 12:27
Can anyone list those games?

**Comment by Syphurith** [comment] 2015-08-29 13:11
@kot2002 *Oh Dean_*. The rxMode function lays inside <repo>/rxTools/source/features/firm.c, then search for string `sizeof(patchNandPrefix)` to get there. If that is caused by the memcmp..
*Use grep (or any other like, such as astrogrep) to search for string. Example: `grep -R rxMode . -C2` search for `rxMode` inside the current path and its subfolders.*
*For me with tortoisegit (any other GUI could do the similar job), i could create a new branch at the version and let git check it out. Once that is done, make the edits and compile/debug/blabla. Then commit to your local repo. Then try to merge it to the main master using pull request.
Even the pull request can not be automatically merged, at least we can see the change, and may even be able to merge that manually once necessary.*
If that does work before just that commit -- well at least we don't have to search for it in a whole repo.

**Comment by DaemonKun** [comment] 2015-08-29 16:46
@173210 Sm4sh and MH4U only.

**Comment by kot2002** [comment] 2015-08-29 19:39
@173210 Monster Hunter 4/4G/4U and Super Smash Bros. on OLD 3DS

**Comment by soarqin** [comment] 2015-08-30 08:02
@motezazer @DaemonKun I have tested MH4G(Japan ver) on my both JPN/TWN consoles and worked fine with extended RAM option enabled

**Comment by kot2002** [comment] 2015-08-30 15:04
@Syphurith, @173210 I tested with cc33af00514e5991f7b2c1eab731f738ee14a3e3 build with cc33af00514e5991f7b2c1eab731f738ee14a3e3#diff-ac6385ab3288b4029e1cbeaedd4d9507L190 line 190-191 reverted.
And still it shows an error message. It seems that memcmp did not made this bug.

**Comment by soarqin** [comment] 2015-08-30 15:10
I tried to revert native_firm myThread patches back to some old commit which works with MH4G, and found it still not working. The I tried to skip native_firm patch codes on reboot and put a patched *002.bin in data folder, then MH4G boots.
I also tried new firm_launch, but with no luck. I think that differences between normal reboot and firm_launch are only the new firm launch menu codes.
So I suggest that the reboot patching codes and launch menu codes occupy some memory blocks which affect extened RAM games' booting

**Comment by soarqin** [comment] 2015-08-30 15:35
OK, tested newest patch with firm launch patching skipped and it works fine:
1. boot emuNAND once, copy generated NATIVE_FIRM.BIN to overwrite 0004013800000002.bin, trim it to 0xEBC00 bytes.
2. apply this commit: https://github.com/roxas75/rxTools/compare/master...soarqin:testing2
3. boot to your emuNAND and MH4G works

**Comment by soarqin** [comment] 2015-08-31 08:38
Finally I found what was wrong:
These games re-launch NATIVE_FIRM on launching to do something, through EMUNAND_READ hack, they reads rxTools/data/0004013800000002.bin.
Our new patching codes did not write patched data into 0004013800000002.bin so the games will run incorrect NATIVE_FIRM which implies error message.

**Comment by 173210** [comment] 2015-08-31 08:51
@soarqin Where is the code to read the file? I couldn't find such a thing.

**Comment by soarqin** [comment] 2015-08-31 08:56
@173210 p9_reboothax_1.s patches firms reading, it searches "sdmc:/rxtools/data/%08x%08x.bin" first, and read from NAND if not found

**Comment by kot2002** [comment] 2015-08-31 09:00
Great work!

**Comment by 173210** [comment] 2015-08-31 09:02
@soarqin Thank you and sorry for bothering you with my patch.
By the way, is it necessary to load the firmware again?

**Comment by soarqin** [comment] 2015-08-31 09:03
@173210 this is just the mechanism of these games, I don't know how to prevent them from re-launching NATIVE_FIRM

**Comment by 173210** [comment] 2015-08-31 09:04
@soarqin I mean, it may be able to relaunch the firmware without loading the one.

**Comment by soarqin** [comment] 2015-08-31 09:05
@173210 hmmm, so we need to apply patches on relaunch, I think it is quite hard.

**Comment by 173210** [comment] 2015-08-31 09:07
@soarqin No, we don't have to do that. we may skip this part.
https://github.com/roxas75/rxTools/blob/master/reboot/source/start.s#L50

**Comment by 173210** [comment] 2015-08-31 09:07
Here is the part in the patch.
https://github.com/roxas75/rxTools/blob/master/rxmode/native_firm/source/p9_reboothax_2.s#L54

**Comment by soarqin** [comment] 2015-08-31 09:08
@173210 if we skip this part, AGB_FIRM and TWL_FIRM patches would be lost also.

**Comment by 173210** [comment] 2015-08-31 09:08
@soarqin I see. Thank you so much.

**Comment by AlbertoSONIC** [comment] 2015-08-31 09:15
@soarqin Yeah exactly. Thank you for having found the issue!

**Closed** 2015-08-31 09:23 UTC
Labels: bug
